/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[10] = "";
	char str1[32]= "";
	SystemInit();
	EEPROM_Init();
	UartInit(9600);
	int choice;

	do{
		UartPuts("Choose the operation from below\r\n");
		UartPuts("0. Exit\r\n");
		UartPuts("1. write string into EEPROM\r\n");
		UartPuts("2. Read from EEPROM\r\n");
		UartGets(str);
		sscanf(str,"%d",&choice);

		switch(choice){
			case 1:
				UartPuts("Enter the string: ");
				UartGets(str1);
				EEPROM_Write(0x0000, (uint8_t*)str1,32);
				break;

			case 2:
				EEPROM_Read(0x0000, (uint8_t*)str1,32);
				UartPuts(str1);
				break;
		}
	}while(choice!=0);

	return 0;
}









