/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "i2c_lcd.h"
#include "switch.h"
#include "adc.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int ret;
	uint16_t val;
	char str[20];
	SystemInit();
	SwitchInit(SWITCH);
	ADC_Init();
	ret=LcdInit();
	while(1) {
		if(ret){
			LcdPuts(LCD_LINE1,"Assignment 2:");
			// wait until switch interrupt generated
			while(exti0_flag == 0)
				;
				val = ADC_GetValue();
				sprintf(str,"ADC = %d",val);
				LcdPuts(LCD_LINE2,str);
				exti0_flag = 0;
				DelayMs(50);
		}
   	}
}
